---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.name }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vaulturl }}
      serviceAccountRef:
        name: {{ .Values.serviceaccountname }}
